name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.24.0
        with:
          php-version: "8.2"

      - name: Install dependencies
        run: composer install

      - name: Run PHP CS Fixer
        run: php artisan fixer:fix
